services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, 50]
        calls:
            - [ setLocale, [ %locale% ] ]
        tags:
            -  { name: twig.extension }

    oc_platform.validator.antiflood:                              # Le nom du service
        class: OC\PlatformBundle\Validator\AntifloodValidator     # La classe du service, ici notre validateur déjà créé
        arguments: [@request_stack, @doctrine.orm.entity_manager] # Les données qu'on injecte au service : la requête et l'EntityManager
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }  # C'est avec l'alias qu'on retrouvera le service

    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html, "2015-10-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }


    oc_platform.censorship_processor:
        class:     OC\PlatformBundle\Bigbrother\CensorshipProcessor
        arguments: [@mailer]

    oc_platform.censorship_listener:
        class:     OC\PlatformBundle\Bigbrother\CensorshipListener
        arguments: [@oc_platform.censorship_processor, [1, 2, 3]]
        tags:
            - { name: kernel.event_listener, event: oc_platform.bigbrother.post_message, method: processMessage }

#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
