<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository {
	public function getApplicationsWithAdvert($limit) {
		return $this->createQueryBuilder('a')
					->join('ap.advert', 'adv')
					->addSelect('adv')
					->orderBy('a.id', 'DESC')
					->setMaxResults($limit)
					->getQuery()
					->getResult();
	}
}
